### ISSUE TITLE
Not accepting API key when passed in script, but works as environmental variable

### ISSUE THREAD

**Issue by freebsdsa** [tmunzer/mistapi_python#1]
Using python version 3.8.16

When I run the following code (I obfuscated the API key in code below):

`import mistapi

mist_api_key = "Fhsu................................................................ITNFbTS8O2N"
mist_api_url = 'api.mist.com'
apiSession = mistapi.APISession(apitoken=mist_api_key,host=mist_api_url,console_log_level=10)
apiSession.login()`

I get the following error:
`apirequest:mist_get: HTTP error occurred: 401 Client Error: Unauthorized for url: https://api.mist.com/api/v1/self
apirequest:mist_get: HTTP error description: {'detail': 'Authentication credentials were not provided.'}
apiresponse:__init__: response = <Response [401]>

-------------------------------- Authenticated ---------------------------------

Welcome  !

Traceback (most recent call last):
  File "./mistAPI.py", line 13, in <module>
    print(mistapi.cli.select_site(apiSession,org_id=mist_org_id))
  File "/usr/local/lib/python3.8/site-packages/mistapi/cli.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mistapi/cli.py", line 228, in select_site
    for privilege in mist_session.privileges:
TypeError: 'Privileges' object is not iterable`

Like I said, if I set the API key as an ENV variable it works. So I know the key is good. Not sure what I am missing here to make this work. Thanks

**Comment by tmunzer** [comment]
I just fixed it in the latest version (0.41.10).
Let me know if it's good for you

**Comment by freebsdsa** [comment]
I updated to the latest release and re-ran the test. I get a new error now with the same code posted above.

`Traceback (most recent call last):
  File "./mistAPI.py", line 4, in <module>
    import mistapi
  File "/usr/local/lib/python3.8/site-packages/mistapi/__init__.py", line 14, in <module>
    from mistapi import api
  File "/usr/local/lib/python3.8/site-packages/mistapi/api/__init__.py", line 13, in <module>
    from mistapi.api import v1
  File "/usr/local/lib/python3.8/site-packages/mistapi/api/v1/__init__.py", line 24, in <module>
    from mistapi.api.v1 import sites
  File "/usr/local/lib/python3.8/site-packages/mistapi/api/v1/sites/__init__.py", line 13, in <module>
    from mistapi.api.v1.sites import webhooks
  File "/usr/local/lib/python3.8/site-packages/mistapi/api/v1/sites/webhooks.py", line 17
    def searchOrgWebhooksDeliveries(mist_session:_APISession, org_id:str, webhook_id:str, org_id:str=None, site_id:str=None, webhook_id:str=None, status_code:int=None, topic:str=None, start:int=None, end:int=None, duration:str="1d", limit:int=100) -> _APIResponse:
    ^
SyntaxError: duplicate argument 'org_id' in function definition`

**Comment by tmunzer** [comment]
Ok, that's another error due to the new API endpoints I added recently. This should have been fixed in 0.41.11.

Thanks

**Comment by freebsdsa** [comment]
Confirmed working now in 0.41.11. Thank you.
