### ISSUE TITLE
MSP and ORG ID

### ISSUE THREAD

**Issue by exodusftw** [tmunzer/mistapi_python#2]
Is there a way to pass an MSP ID and org IDs into the session objects without having to manually pass them to the CLI class?

As these are static values, we could define them as global variables and that would make it where we could invoke these programmatically without having to prompt for user input.

**Comment by tmunzer** [comment]
Hi @exodusftw ,
no, currently the python package is mainly here to manage the authentication information (Mist Cloud, User login/pwd or API Token, ...), and you must pass the msp_id/org_id/site_id in the function parameters.

However, it is still possible to store the msp_id or the org_id in an environment file and to load it from the python script, or to pass it as a parameter. You can find an example here: https://github.com/tmunzer/mist_library/blob/master/scripts/devices/rename_devices.py

**Comment by exodusftw** [comment]
Thanks for the feedback - was able to get it working after reviewing your example
